### PR TITLE
add CommonUser tests

### PR DESCRIPTION
**Pull request by karrrie**
add common user tests

### CODE REVIEW

**Review by Daiiii99 — CHANGES_REQUESTED** [review]
This is not unit test; please change the format into Junit test. :D

**Comment by Rannu0** [comment]
neat and easy to follow, good job!

**Review by Rannu0 — DISMISSED** [review]

**Comment by karrrie** [comment]
Please check and review the content of tests~ I have fixed the problems.

**Review by MikeJiahaoXu — DISMISSED** [review]
good job

**Comment by karrrie** [comment]
please check and approve the request!

**Review by Daiiii99 — DISMISSED** [review]
All tests passed.

**Review by MikeJiahaoXu — APPROVED** [review]
good

**Review by Daiiii99 — APPROVED** [review]
Naming convention improved.

**Review by mugengliu — APPROVED** [review]

**Pull request merged**
