### PR TITLE
user, like, and unlike

### PR DESCRIPTION
**Pull request by Daiiii99**
DONE:
-user: create and search
-find post by user_id
-like and unlike a post (updates every time; new property “like" under reply)

### CODE REVIEW

**Review by mugengliu — COMMENTED** [review]
The user collection should be inserted following values:
1. password
2. photo
3. register time
4. post they have sent 
5. settings ( for further consideration)

**Review by mugengliu — COMMENTED** [review]
Upload the new database location to the server, and run with no bugs.
Test with sending and receiving messages, run with no bugs.

**Review by mugengliu — CHANGES_REQUESTED** [review]
Need a delete method, user can delete their post.

**Comment by Daiiii99** [comment]
> Need a delete method, user can delete their post.

Interesting idea, but this actually complicates things quite a bit.
This creates the possible race condition of a user replying to a post that is already deleted. 
Would like to discuss more with the team to be aligned on what the behavior should be across the board before implementing this function.

i.e
- Should the db/backend throw an error to the user?
- Should we silently process the message and discard the reply instead?

**Comment by Daiiii99** [comment]
> The user collection should be inserted following values:
> 
> 1. password
> 2. photo
> 3. register time
> 4. post they have sent
> 5. settings ( for further consideration)

Discussed offline, the `insert_user` method already accepts a Document object as an input argument. 
Caller code can put in as many key-value pairs as needed, this should resolve bullet points 1, 2, 3, 5*

When the backend team flush out the `User` class, we will then swap to using that

4 sounds a bit redundant, we are already storing the information to whom each post belongs in the form of a `user_id`
Given the existing complication of wanting the function to delete a post, recommend using the existing function `find_latest_posts_by_user_id` to direct fetch from the `post `collection.

5* If we ever need to update this field, I can push out a function to override the existing key-value pair, but sounds like this is currently more about future-proofing

**Comment by mugengliu** [comment]
> > Need a delete method, user can delete their post.
> 
> Interesting idea, but this actually complicates things quite a bit. This creates the possible race condition of a user replying to a post that is already deleted. Would like to discuss more with the team to be aligned on what the behavior should be across the board before implementing this function.
> 
> i.e
> 
> * Should the db/backend throw an error to the user?
> * Should we silently process the message and discard the reply instead?

1. It depends on what extent we want to improve the user experience. In fact, we could simply tell the user that there's something wrong with the current page, followed by a window refresh. But for clean architecture, we could aim for a good user experience as well as error handling. Depends on the time we have, because we need to design how we alert the user. 
2. It is an optional challenge for the backend, nevertheless, we put replies into our blueprint, and now we have to consider how we display those replies.

**Comment by mugengliu** [comment]
> > The user collection should be inserted following values:
> > 
> > 1. password
> > 2. photo
> > 3. register time
> > 4. post they have sent
> > 5. settings ( for further consideration)
> 
> Discussed offline, the `insert_user` method already accepts a Document object as an input argument. Caller code can put in as many key-value pairs as needed, this should resolve bullet points 1, 2, 3, 5*
> 
> When the backend team flush out the `User` class, we will then swap to using that
> 
> 4 sounds a bit redundant, we are already storing the information to whom each post belongs in the form of a `user_id` Given the existing complication of wanting the function to delete a post, recommend using the existing function `find_latest_posts_by_user_id` to direct fetch from the `post `collection.
> 
> 5* If we ever need to update this field, I can push out a function to override the existing key-value pair, but sounds like this is currently more about future-proofing

Sure, we could extend later as long as the alteration is not hard.

**Review by mugengliu — APPROVED** [review]
I will approve it now as the server runs stably and I need those codes to elaborate my work.

**Review by MikeJiahaoXu — APPROVED** [review]
I agree with Mugen's comments.

**Comment by roxanehe** [comment]
I need this like, unlike part to finish my functionality.

**Review by roxanehe — APPROVED** [review]
I need this functionality in order to get my part done

**Review by mugengliu — CHANGES_REQUESTED** [review]
Waiting for "main" branch to be fixed

**Review by mugengliu — APPROVED** [review]

**Pull request merged**
