### PR TITLE
Database unit test done

### PR DESCRIPTION
**Pull request by Daiiii99**
-Database unit tests done.
-Unit test configuration has set up: can run all unit tests at the same time.

### CODE REVIEW

**Review by Rannu0 — DISMISSED** [review]

**Review by MikeJiahaoXu — DISMISSED** [review]
nice!

**Review by karrrie — DISMISSED** [review]
Several tests failed, you can check them in autograding, they might need some changes.

**Comment by Daiiii99** [comment]
> 

The failure is due to env variable configuration. I asked about this on Piazza. Still waiting for replies.

**Review by MikeJiahaoXu — DISMISSED** [review]

**Review by MikeJiahaoXu — APPROVED** [review]

**Review by mugengliu — APPROVED** [review]

**Review by roxanehe — APPROVED** [review]
thanks!!

**Pull request merged**
