### PR TITLE
Servlet environment + Webpage Improvement

### LINKED ISSUE #16: Cookie, frontend temporary storage
Cookie as data storage could save frontend status temporarily. Cookie could realize login system, which refresh the webpage won't require second time login. It will largely enhance the user experience thus is considered the next goal after realizing actual time binding.
实现cookie数据存储，用户网页刷新时不会被要求重新登录。更加增强用户体验。

### PR DESCRIPTION
**Pull request by mugengliu**
Improvement:
1. Realize the frontend-backend two-way binding
- Set up the webpage and frontend
- Set up the servlet environment, and enable the front to send data to the backend in real-time
- Enable the backend to request messages from the database and send them to frontend
3. Improve the frontend functionality, elaborate the webpage
- Can send the message, and message will be recorded
- Can see the message history
- Can see who send the message
- Extend some internal test 

Current Web address: [k125.love:8080/k125](url)

### CODE REVIEW

**Review by MikeJiahaoXu — APPROVED** [review]
good!

**Review by karrrie — APPROVED** [review]

**Comment by Daiiii99** [comment]
Unchecked, but pull first

**Comment by Daiiii99** [comment]
Unchecked, but pull first

**Comment by Daiiii99** [comment]
点错了

**Review by Daiiii99 — APPROVED** [review]
Unchecked, pull first

**Pull request merged**
