### PR TITLE
1. Fix the bugs:

### PR DESCRIPTION
**Pull request by mugengliu**
a. several connection bugs
   b. sending reply does not show name properly
2. Add app security: a. use session as encrypt system b. backend send cookie to frontend c. prevent user keep registering
3. Improve coding: a. totally delete jQuery code, improve code smell
4. Ethics consideration: a. adjust UI at PC end

### CODE REVIEW

**Review by MikeJiahaoXu — APPROVED** [review]

**Review by karrrie — APPROVED** [review]
Goood

**Review by roxanehe — APPROVED** [review]
Looks good! thanks friend

**Comment by mugengliu** [comment]
checks failed, temporarily close this comment

**Comment by mugengliu** [comment]
Auto grading fails, we declare the problems on the piazza, and also post to the Issues section. 
Please refer to the issue #63  and [piazza](https://piazza.com/class/l5v1b8gfz6b60m/post/643).

**Pull request merged**
